#!/usr/bin/env bash

# Source the configure_cron_task.sh_optparse file ---------------------------------------------------
source configure_cron_task.sh_optparse

# Command
cmd="/usr/sbin/write_cron_conf"

restart_cron() {
  service crond restart
}

declare -A month_hash=([January]=1 [February]=2 [March]=3 [April]=4 [May]=5 [June]=6 [July]=7 [August]=8 [September]=9 [October]=10 [November]=11 [December]=12)
declare -A day_hash=([Monday]=2 [Tuesday]=3 [Wednesday]=4 [Thursday]=5 [Friday]=6 [Saturday]=1 [Sunday]=0)
  
# Write cron configuratin
echo "Writing cron configuration"
echo "Executing command $cmd $minute $hour $day_of_month $month $day_of_week $task"
if [ "$month" == "*" -a "$day_of_week" == "*" ]; then
  eval "$cmd \"$minute\" \"$hour\" \"$day_of_month\" \"*\" \"*\" \"$task\""
elif [ "$month" == "*" -a ! "$day_of_week" == "*"  ]; then
  eval "$cmd \"$minute\" \"$hour\" \"$day_of_month\" \"*\" \"${day_hash[$day_of_week]}\" \"$task\""
elif [ ! "$month" == "*" -a "$day_of_week" == "*"  ]; then
  eval "$cmd \"$minute\" \"$hour\" \"$day_of_month\" \"${month_hash[$month]}\" \"*\" \"$task\""
else
  eval "$cmd \"$minute\" \"$hour\" \"$day_of_month\" \"${month_hash[$month]}\" \"${day_hash[$day_of_week]}\" \"$task\""
fi
# Restart cron daemon
echo "Restarting cron daemon"
restart_cron

exit 0

