#!/bin/bash

vm_name=${1:?}

vm_name_large=$(VBoxManage list vms | grep $vm_name | cut -d '"' -f 2)

vagrant ssh -c "rm -f /etc/udev/rules.d/70-persistent-net.rules"
vagrant halt
vagrant destroy -f $vm_name
rm -f centos63-guestadditions-mbc-x86_64.box
vagrant package --base $vm_name_large --output /home/danyboy/WorkspaceVagrant/Centos63/centos63-guestadditions-mbc-x86_64.box
rm -rf ~/.vagrand/boxes/$vm_name
