#!/bin/bash

# update_centos7_repos
# Actualizacion de repos
rsync -av rsync://example.com/~centos/7/os/x86_64/ /run/media/danyboy/2A9804E79804B37D/Daniel/repos/centos/7/os/x86_64/
rsync -av rsync://example.com/~centos/7/updates/x86_64/ /run/media/danyboy/2A9804E79804B37D/Daniel/repos/centos/7/updates/x86_64/
rsync -av rsync://example.com/~epel/7/x86_64/ /run/media/danyboy/2A9804E79804B37D/Daniel/repos/centos/7/epel/x86_64/
rsync -av rsync://example.com/~centos/7/extras/x86_64/ /run/media/danyboy/2A9804E79804B37D/Daniel/repos/centos/7/extras/x86_64/
rsync -av rsync://example.com/repoforge/el7/rpmforge/x86_64/ /run/media/danyboy/2A9804E79804B37D/Daniel/repos/centos/7/rpmforge/x86_64/
rsync -av rsync://example.com/addons7/ /run/media/danyboy/2A9804E79804B37D/Daniel/repos/centos/7/addons/
rsync -av rsync://example.com/nux/el7/x86_64/ /run/media/danyboy/2A9804E79804B37D/Daniel/repos/centos/7/nux/el7/x86_64/
